-keepattributes SourceFile
-dontwarn java.util.**
-dontwarn java.time.**
-dontwarn javax.**
-dontwarn com.squareup.**
-dontwarn rx.**
-dontwarn com.sun.tools.**
-dontwarn com.sun.misc.**
-dontwarn com.sun.source.**
-dontwarn com.squareup.**
-dontwarn com.google.auto.**
-dontwarn com.google.common.**
-dontwarn com.google.j2objc.**
-dontskipnonpubliclibraryclasses
#retrolambda
-dontwarn java.lang.invoke.*
-dontwarn **$$Lambda$*